### ISSUE TITLE
Map download failed

### ISSUE THREAD

**Issue by Reverjet** [crymp-net/client-server#53]
Tried to join CarpNetwork server with custom map, a error occured. Old client downloads the map normally.
![image](https://user-images.githubusercontent.com/54474453/196041512-a3f7a9ba-ef13-4a8c-bb3b-9453edbc5a3a.png)

**Comment by ccomrade** [comment]
`|` is not allowed in filenames in Windows, so it's not possible to create such file. Name of the map is invalid. Question is, whether the client should try to avoid this issue by replacing these invalid characters with `_` for example. In any case, thanks for the report.

**Comment by ccomrade** [comment]
Well, it's a bug actually. This `|1.1` is the map versioning feature, which is not implemented here.

**Comment by ccomrade** [comment]
Map versioning implemented for v18. Closing
