### ISSUE TITLE
Keyboard layout

### ISSUE THREAD

**Issue by Reverjet** [crymp-net/client-server#79]
Unable to change keyboard layout (language) while in-game which prevents from using game chat if English layout wasn't chosen before starting game or until collapsing the game to change layout on desktop. A few other people also reported on the same problem.

**Comment by ccomrade** [comment]
Interesting issue. Probably related to our custom game window event handler in `Code/CrySystem/GameWindow.cpp`. It's based on the reverse engineered game startup code hidden in the original CryGame, which we don't use here.

**Comment by ccomrade** [comment]
Fixed in `v19-111-g6ca4109`
